### ISSUE TITLE
Migrace na HTTPS

### ISSUE THREAD

**Issue by jnv** [jnv/bitoff.cz#9]

**Comment by jirutka** [comment]
Using third-party service that works on principle of MitM “attack”… not very good. 😞

**Comment by jnv** [comment]
Yes, it's called CDN.

**Comment by jirutka** [comment]
This year seems to be fecund for security disasters, so I'm quite confident that I will laugh last... ;)

**Comment by jnv** [comment]
Sure, keep your hopes up. I'm willing to risk that since I don't collect or process any sensitive data at all. At least I'm publishing something and I'm not just nagging on the interwebs.
